### ISSUE TITLE
Add Profile to List

### ISSUE THREAD

**Issue by manimalsmith23** [klaviyo/klaviyo-api-node#14]
https://developers.klaviyo.com/en/reference/create_list_relationships

Not sure how this endpoint works? In the example `body: JSON.stringify({data: [{type: 'profile'}]})` there is no id, but in the body params description it says type and id are required. What is the id here referring to?

All I want to do is add an array of users (identified by their emails) to a specific list. Eg. 
```
[
  { email: "joe@email.com"},
]
```

 How do I use this endpoint? Thank you.

**Comment by vpylypenko-klaviyo** [comment]
Thanks for reaching out.

`POST /api/lists/{id}/relationships/profiles/` endpoint does require `id` in the request body. This is profile identifier. 

Here is an example of possible request body:
```
{
    "data": [
        {
            "type": "profile",
            "id": "01FX31VRTNTTB32V2JEEGW7S0P"
        }
    ]
}
```
One way to obtain the profile identifier is to search for the profile by email
`GET /api/profiles/?filter=equals(email,"joe@email.com")`
[Here is documentation on how to use filters](https://developers.klaviyo.com/en/reference/api_overview#filtering)
The response will look like the following:
```
{
    "data": [
        {
            "type": "profile",
            "id": "01FQ0NQP87Y7HMJFMQXRV41V78",
            "attributes": {
                "email": "joe@email.com",
                ...
                "created": "2021-12-16T03:49:22+00:00",
            },
        }
    ],
    ...
}

```
Another approach is to use the [Subscribe Profiles endpoint](https://developers.klaviyo.com/en/reference/subscribe_profiles) if you're trying to give a profile consent to receive email marketing.
