### ISSUE TITLE
npm install yields ECONNRESET

### ISSUE THREAD

**Issue by andreemic** [klaviyo/klaviyo-api-node#15]
<img width="607" alt="Screenshot 2023-03-01 at 06 28 36" src="https://user-images.githubusercontent.com/27695722/222098634-38445ee9-d322-4548-b758-19e6b143d721.png">

**Comment by Ian-Montgomery-Klaviyo** [comment]
This is an error related to connecting to the NPM registry not with the klaviyo-api package itself. You will need to ensure that your development environment has access to the npm registry in order to pull down the package.
