### ISSUE TITLE
Why are there client-only functions in a server-side SDK?

### ISSUE THREAD

**Issue by cirkul-marc** [klaviyo/klaviyo-api-node#19]
The API documentation states these endpoints are to be used from client-side environments only:
https://developers.klaviyo.com/en/reference/create_client_subscription
https://developers.klaviyo.com/en/reference/create_client_event
https://developers.klaviyo.com/en/reference/create_client_profile

So why are they included here, if they shouldn't be used?
https://github.com/klaviyo/klaviyo-api-node#clientapi

**Comment by Ian-Montgomery-Klaviyo** [comment]
These have been removed as of the `4.0.0` release to avoid this confusion. Thanks for the feedback!
