### ISSUE TITLE
Request: More extensive SDK Documentation

### ISSUE THREAD

**Issue by ZEAL-MATCH-LTD** [klaviyo/klaviyo-api-node#2]
Hello there, 

Getting to grips with Klaviyo and as well as needing Typescript support , i really think the SDK API could do with some better examples (like what you have on your site for `node` etc but a dropdown example for the SDK would be great.

i.e https://developers.klaviyo.com/en/reference/create_profile could do with the SDK implementation somewhere.

Also i'm finding myself wondering if `updateProfile` for example will fail if the profile doesn't already exists... will it? or will it create in it's place...?

Many thanks

**Comment by jon-batscha** [comment]
Hey! This is great feedback, we really appreciate it.

1. Regarding Typescript support: This is one of the most common requests we hear, so it is on our roadmap (no firm release schedule yet). Until that’s available, we have had developers find some success generating their own TypeScript SDK using our [OpenAPI](https://github.com/klaviyo/openapi) spec along with either [openapi-generator](https://github.com/OpenAPITools/openapi-generator) or [swagger-codegen](https://github.com/swagger-api/swagger-codegen).

2. As for better, SDK-specific examples: that’s another item further out on our roadmap.

3. updateProfile : Great question! This function requires a profile ID to work, so if a given profile doesn’t exist, there is no profile ID to call this function with. If you call it with a non-existing profile ID, you will get a 404 error. Your question alludes to a related point which we have heard from other developers, which is this: when you have some profile data that you want to send to Klaviyo, you may not know if that profile is new (in which case you would want to call createProfile ) or if it already exists (in which case you would want to call updateProfile). For this use case, I recommend always calling createProfile first, and if a profile already exists with the given identifier, you will get back an error message with the profile ID you need to call updateProfile.

here is an example error response when calling create profile using an existing identifier:
```
{
    "errors": [
        {
            "id": "SOME_ERROR_ID",
            "status": 409,
            "code": "duplicate_profile",
            "title": "Conflict.",
            "detail": "A profile already exists with one of these identifiers.",
            "source": {
                "pointer": "/data/attributes"
            },
            "meta": {
                "duplicate_profile_id": "EXISTING_PROFILE_ID"
            }
        }
    ]
}

```

Hopefully this answers your questions. And don't be shy in sending us any further issues, questions, and suggestions you come across. Thanks again!

Cheers,
Jon
