### ISSUE TITLE
documentation for SDK lacking

### ISSUE THREAD

**Issue by pvijeh** [klaviyo/klaviyo-api-node#22]
guys,  the docs for this SDK are pretty lacking... can you beef them up a bit?

**Comment by Ian-Montgomery-Klaviyo** [comment]
Thanks for the feedback. We are consistently working to improve our SDKs and the associated docs over time. We just released JSON:API examples in our SDK README.md as an example. If any of these features are still unclear please let us know.
Can you share a bit about what you were trying to do with the SDK that was confusing? We can take your feedback into consideration as we prioritize items.
