### ISSUE TITLE
Critical Dependency: Klaviyo > Superagent > Formidable

### ISSUE THREAD

**Issue by rafaelderolez** [klaviyo/klaviyo-api-node#23]
Getting an error in my logs regarding `formidable`, which is used by `superagent`, which is used in this package's [ApiClient.js](https://github.com/klaviyo/klaviyo-api-node/blob/251ee0d47769845f34251bd6b93eed8aa901a7b4/src/ApiClient.js#L16)

Seems to have been resolved in [this superagent PR](https://github.com/ladjs/superagent/issues/1609)

```
Import trace for requested module:
./node_modules/formidable/src/Formidable.js
./node_modules/formidable/src/index.js
./node_modules/superagent/lib/node/index.js
./node_modules/klaviyo-api/dist/ApiClient.js
./node_modules/klaviyo-api/dist/index.js
./path/to/my/local/function/using/Klaviyo/Events.createEvent.ts
- warn ./node_modules/formidable/src/Formidable.js
Critical dependency: the request of a dependency is an expression
```

``` 
$ npm ls formidable
└─┬ klaviyo-api@3.0.0
  └─┬ superagent@7.1.5
    └── formidable@2.1.1
```

**Comment by rafaelderolez** [comment]
Thanks @Ian-Montgomery-Klaviyo! I'll upgrade somewhere this week. I'll let you know how it goes and will close the issue accordingly 👍

**Comment by rafaelderolez** [comment]
@Ian-Montgomery-Klaviyo Unfortunately, we're still getting the same error with the new version upgrade.

```
$ npm ls formidable
└─┬ klaviyo-api@4.0.1
  └─┬ superagent@8.0.9
    └── formidable@2.1.2
```
```
warn ./node_modules/formidable/src/Formidable.js
Critical dependency: the request of a dependency is an expression

Import trace for requested module:
./node_modules/formidable/src/Formidable.js
./node_modules/formidable/src/index.js
./node_modules/superagent/lib/node/index.js
./node_modules/klaviyo-api/dist/ApiClient.js
./node_modules/klaviyo-api/dist/index.js
```

**Comment by Ian-Montgomery-Klaviyo** [comment]
The 6.0.0 Update overhauls the entire app to be native typescript. This removes this superagent as a dependency in favor of axios.
