### ISSUE TITLE
TypeScript SDK Missing EmailEnum export

### ISSUE THREAD

**Issue by sebastiansandqvist** [klaviyo/klaviyo-api-node#29]
For the `subscribeProfiles` endpoint, `data.attributes.profiles.data[number].attributes.subscriptions.email` accepts an array of `EmailEnum` strings, but the `string` type is not allowed in that array and `klaviyo-api` does not export an `EmailEnum`.

<img width="666" alt="Screenshot 2023-08-01 at 9 51 49 PM" src="https://github.com/klaviyo/klaviyo-api-node/assets/2024396/f482844d-8e04-4398-809d-9b3866ff208d">

**Comment by Ian-Montgomery-Klaviyo** [comment]
We can look into a way to make this more clear since currently email and sms have the same subscriptions channels. but the enum you are looking for is `SubscriptionChannels.EmailEnum.Marketing`
