### ISSUE TITLE
Relationship(s) Field Not an Array

### ISSUE THREAD

**Issue by TheDunco** [klaviyo/klaviyo-api-node#40]
It's interesting to me that the `relationships` field in endpionts like [subscribe profiles](https://developers.klaviyo.com/en/reference/subscribe_profiles#:~:text=ADD%20OBJECT-,relationships,-object) is "relationship**s**" instead of just `relationship` because that field is NOT an array so it shouldn't be plural.

It would be fantastic if we could actually provide multiple relationships in this request in the form of an array of relationship objects. If that's not possible, I'd like to see the field here renamed or aliased to `relationship` for clarity.

**Comment by vpylypenko-klaviyo** [comment]
I see why it is confusing to have plural name `relationships` in this case when it is possible to provide reference to only one list. The reason we used plural name here and everywhere in our API was to be compliant with JsonAPI specification. Please find more details about format for `relationships` [Json API - creating resources](https://jsonapi.org/format/#crud-creating).

Also, if we decided to deviate form the specification, renamed the field to `relationship` and later decided to support additional relationship (e.g. `tag`) for this endpoint we would need to rename the field back to `relationships`. That would be a breaking change.

**Comment by TheDunco** [comment]
> to be compliant with JsonAPI specification

Ah, I see, that makes sense. My gripe lies with the JsonAPI specification then! 🤣 

The request I have for the Klaviyo team would then be to either add a callout in the documentation that this field is NOT an array, and/or add a section about best practices for adding multiple relationships so more me's don't pop up confused about this 😆

**Comment by TheDunco** [comment]
Also, I agree that the least amount of breaking API changes is the best experience for everyone!
