### ISSUE TITLE
Sessions are not re-applied to requests when backing off

### ISSUE THREAD

**Issue by stevekanter-arcticleaf** [klaviyo/klaviyo-api-node#43]
In developing a custom OAuth session for this project for Klaviyo's OAuth alpha, I'm utilizing the session's `getRetryOptions` which is passed to the exponential backoff's retry method to refresh and persist the token. I'm also using the session's `applyToRequest` to put the Authorization header on the request options.

However, if a token is refreshed, the session's `applyToRequest` is **not** being re-run when the request is retried through axios again. This applies to every single method that is generated, but as an example: https://github.com/klaviyo/klaviyo-api-node/blob/666d837cfec47b01c1d90c6805e2d4332c3e1715/api/listsApi.ts#L114C21-L114C21

My expectation would be to see the `applyToRequest` call to be made **inside** of the backoff so that the session has an opportunity to change settings each time the request is made. i.e.:

```typescript
        return backOff<{ response: AxiosResponse; body: PostListCreateResponse;  }>( () => {
            return new Promise<{ response: AxiosResponse; body: PostListCreateResponse;  }>((resolve, reject) => {
                ** this.session.applyToRequest(config) **
                axios(config)
                    .....
            });
        }, this.session.getRetryOptions());
```

**Comment by Ian-Montgomery-Klaviyo** [comment]
Good news, we have developed an `OAuthSession` object along with other various OAuth helpers to help with the authorization flow and keeping `Access Tokens` up to date. It will be released as under a beta version (while OAuth is still in early access) this week. We will post in this thread again once it's available.

**Comment by stevekanter-arcticleaf** [comment]
@Ian-Montgomery-Klaviyo that's great news but FYI the project we're currently contracted from Klaviyo to work on is under time pressure. We're working with Michael Worthley at Klaviyo. Please keep me appraised as to the timing.

**Comment by Ian-Montgomery-Klaviyo** [comment]
The release is out!

Use `npm i klaviyo-api@beta` to pull the package.

Check out the beta branch and some extra OAuth documentation [here](https://github.com/klaviyo/klaviyo-api-node/tree/oauth-beta).

Lastly to potentially help speed up development we created a [sample application](https://github.com/klaviyo-labs/node-integration-example) that uses this code.
