### ISSUE TITLE
PatchProperties unset for profileApi.updateProfile not working

### ISSUE THREAD

**Issue by jack092123** [klaviyo/klaviyo-api-node#45]
version: `v7.0.0`

I was trying to unset a property from a profile with `updateQuery` function but not working

```
const updateQuery = {
  data: {
    id: 'PROFILE_ID',
    type: ProfileEnum.Profile,
    attributes: {},
    meta: {
      patchProperties: {
        unset: 'PROPERTY NAME',
      },
    },
  },
}

await profileApi.updateProfile(profileId, updateQuery)
```

while debugging this issue found that the result of `ObjectSerializer.serialize` will be like this
```
{
  "data": {
    "type": "profile",
    "id": "PROFILE_ID",
    "attributes": {},
    "meta": {
      "patch_properties": {
        "unset": {}
      }
    }
  }
}
```
`unset` will be transform to an object and the patch request for unset property will do nothing

**Comment by Ian-Montgomery-Klaviyo** [comment]
Unset is now set to take an array of string. The resulting value will be serialized correctly and will work correctly with the api.
