### ISSUE TITLE
Incompatible with Firebase Cloud Functions

### ISSUE THREAD

**Issue by ciriousjoker** [klaviyo/klaviyo-api-node#5]
Trying to deploy a function that uses this package will throw with this error message:

```log
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for fsevents@2.3.2: wanted {"os":"darwin"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS: darwin
npm ERR! notsup Valid Arch: undefined
npm ERR! notsup Actual OS: linux
npm ERR! notsup Actual Arch: x64
```

`fsevents` is a macOS-only package and Google's cloud infrastructure obviously runs on Linux. This package doesn't directly depend on it, but it's a dependency of `@babel/cli`, which for some reason made it into `dependencies` instead of `devDependencies` as suggested by the [documentation](https://babeljs.io/docs/en/babel-cli).

[Here is the PR](https://github.com/klaviyo/klaviyo-api-node/pull/4) that fixes this issue.

---

I think Klaviyo is amazing, but I'm really disappointed with this package.

- It's annoying to use because it has no typings & intellisense is broken
- The function parameters differ from the official documentation for seemingly no reason
- It uses transpilation which makes stepping into functions annoying
- The issue from above

I'm sorry, but this thing looks hastily put together or autogenerated by an intern and if I were you, I'd rewrite it from scratch as I honestly can't find anything salvageable in this repo.

**Comment by Ian-Montgomery-Klaviyo** [comment]
We created a 1.0.2 release to fix this the `@babel/cli` issue 

The sdk is autogenerated so sometimes has some weird quirks, if you have a specific issue we can try and fix it in a new release. I've updated the readme a bit to include some info about how the optional parameters name are generated in hope that helps understand where the sdk varies from the actual rest api itself.  

The sdk uses babel to generate a commonjs version of the client for people that dont use ES6, but if your not using `require` it shouldn’t be transpiled. It does by default use a wrapped api client, this maybe be causing intellisense issues and maybe even the debugging issues, you can bypass this. 

```
import {ConfigWrapper, CatalogsApi} from 'klaviyo-api'

const catalogApi = new CatalogsApi(ConfigWrapper("KLAVIYO PRIVATE KEY GOES HERE"))
const r = await catalogApi.createCatalogCategory(body)
```

**Comment by ciriousjoker** [comment]
1. In that case, [this PR](#4) can be closed
2. Are there plans to create a typescript version for this?
3. I'm already using the import format you're suggesting, but Intellisense doesn't work.

**Comment by Ian-Montgomery-Klaviyo** [comment]
We are planning on making a Typescript SDK this quarter.

We will look into the intellisense issue farther. (since that is a separate issue, I will close this one)
