### ISSUE TITLE
Metric and Profile Not Serializing Correctly for CreateEvent

### ISSUE THREAD

**Issue by BodiePaden** [klaviyo/klaviyo-api-node#50]
I'm trying to call eventsApi.createEvent(event), and the "event" object is generating JSON in the request that is basically...

`{
    "data":{
        "type":"event",
        "attributes":{
            "time":"2023-11-15T23:40:12.189Z",
            "unique_id":"696b3941-6ec8-42cc-854f-1f90be51d8de",
            "metric":{
                "data":{
                    "type":"event",
                    "attributes":{
                        "name":"Started Membership"
                    }
                }
            }
        }
    }
}`

I've cut out the "profile" bit for simplicity, but it has the same exact issue.  The issue is that the API responds with an error because it expects "name" to be nested under "metric", not under metric.data.attributes.

**Comment by Ian-Montgomery-Klaviyo** [comment]
I'm not sure whats up with that specific error message, but It looks like there are some issues in the object. Since this is only a partial payload some of suggestions might be included outside of the snippet given. 

1. An event object needs a properties object where you are sending information about the created event. 
2. The metric sub-object should have `type: "metric"`.  The included profile sub-object should have `type: "profile" as well.

Here is an example of a lot of this date in an api call.

```
const eventsApi = new EventsApi(new ApiKeySession(privateKey))

let event: EventCreateQueryV2 = {
  data: {
    type: "event",
    attributes: {
      properties: {
        "membership_type": "test" // what ever data you are tying to send in this event
      },
      time: new Date("2023-11-15T23:40:12.189Z"),
      uniqueId:"696b3941-6ec8-42cc-854f-1f90be51d8de",
      metric : {
        "data": {
          "type": "metric",
          "attributes": {
            "name": "Started Membership"
          }
        }
      },
      profile: {
        data: {
          type: 'profile',
          attributes: {
            email: "EMAIL goes here unless you identify by another means"
          }
        }
      }
    }
  }
}

eventsApi.createEvent(event).then(result => {
  console.log(result.body)
}).catch(error => {
  console.log(error.response.status)
});
```

**Comment by BodiePaden** [comment]
It was your #2 point that got me.  I thought I saw code to default those values to "metric" for metric and "profile" for profile, so I left them out.  I put them back in and it's working now.  I wonder if they maybe should default?  Seems odd to have to specify that the "metric" object whose name is "metric" needs to be told that the type is also "metric".  In any case; closing this issue.  Thanks for the prompt reply!
