### ISSUE TITLE
comments removed in the distributed TS declarations

### ISSUE THREAD

**Issue by hevele-moda** [klaviyo/klaviyo-api-node#58]
I think it would be helpful to keep the comments in the emitted `.d.ts` files, cause the comments on the apis/models serve as a documentation for developers.
It should be as simple as removing `"removeComments": true` from [tsconfig.json](https://github.com/klaviyo/klaviyo-api-node/blob/main/tsconfig.json).

**Comment by Ian-Montgomery-Klaviyo** [comment]
This has been included in v9.0.0 and above, thanks for the feedback.
