### ISSUE TITLE
Getting axios is not function issue 

### ISSUE THREAD

**Issue by AkashLakade** [klaviyo/klaviyo-api-node#63]
App.tsx:20 TypeError: axios is not a function
    at profilesApi.ts:182:1
    at new Promise (<anonymous>)
    at BackOff.request (profilesApi.ts:181:1)
    at BackOff.<anonymous> (backoff.ts:32:1)
    at step (events.js:497:1)
    at Object.next (events.js:497:1)
    at fulfilled (events.js:497:1)
    
    see the console
    
    Node version- 20
    
    Provide the steps to integrate in react app 
    
    Need Help to solve this issue

**Comment by Ian-Montgomery-Klaviyo** [comment]
This application is build specifically for the node.js backend environment, and won't function in a frontend react app. Klaviyo has a different series of endpoints (not included in this package) for calling from the frontend. These are designated with the `/client/` route ([here is an example](https://developers.klaviyo.com/en/reference/create_client_subscription)), some common functionality is included a lightweight web package that you can read about [here](https://developers.klaviyo.com/en/docs/javascript_api).
