### ISSUE TITLE
createProfile doesn't write all the fields

### ISSUE THREAD

**Issue by zeroerrequattro** [klaviyo/klaviyo-api-node#69]
I'm experiencing an issue with `createProfile`:
the profile is created but lacks of all the other properties I attach in the payload.

This is my payload:
```typescript
import {
  ApiKeySession,
  ProfilesApi,
  ProfileCreateQuery,
  ProfileEnum,
} from 'klaviyo-api'

const session = new ApiKeySession(apiKey)
const profilesApi = new ProfilesApi(session)
    
let newProfile: ProfileCreateQuery = {
  data: {
    type: ProfileEnum.Profile,
    attributes: {
      email: 'otto@fakemail.com',
      location: {
        country: 'Germany',
      },
      properties: {
        language: 'german',
      },
    },
  },
}
  
ProfilesApi.createProfile(newProfile)
```
  
But when I check on the profile just created, I don't see the `location` and `language` fields set.

I want to add that the private API Key has Full Access.

**Comment by 50bbx** [comment]
Just to add on this: when making the same call directly using the REST endpoint [Create Profile](https://developers.klaviyo.com/en/reference/create_profile) we see a different result: the `location` and `language` properties are correctly set

**Comment by zeroerrequattro** [comment]
I managed to create a profile using the node API, it was a fault by my side.
Sorry for opening a useless ticket
