### ISSUE TITLE
Rate limit retry is not working

### ISSUE THREAD

**Issue by eapariciodev** [klaviyo/klaviyo-api-node#7]
Two issues:

1. The rate-limit header information is not provided when making a request via the SDK methods. This means you have no way of knowing when you are nearing the limit (to maybe slow down requests) and just have to wait until it fails with a 429 error. At which point, you have no idea how long to wait until the rate-limits are reset.
2. The automatic retry mechanism doesn't seem to work, as far as I can tell. I was doing some testing with the Profiles.getProfiles method and just hammering it on a loop. Regardless of the retry configuration, I got through 150 requests until failure. There was no attempt by the SDK client to retry or do any sort of throttling/backing off.

**Comment by Ian-Montgomery-Klaviyo** [comment]
This is be fixed with our 2.0.0 release. 

Exponential backoff should be back working again, and now the headers are included in the responses so you can code any additional rate limit logic you see fit. Checkout the Changelog.md for the full explanation of the changes.
