### ISSUE TITLE
The subscribeProfiles endpoint is not working correctly

### ISSUE THREAD

**Issue by ericneubauerbumphealth** [klaviyo/klaviyo-api-node#71]
Hi!

I found two problems with the subscribeProfiles endpoint when I tried switching to this library from doing direct HTTP requests.

1. The `custom_source` property (which sets the `$source` profile property) in the subscribeProfiles payload seems to be discarded.
2. I could not get SMS channel subscriptions to work. When attempting this I would get the following error response from the API `Phone number must be provided when subscribing to the SMS channel.`.

I do not have either of these problems when making direct HTTP requests even though I'm using the same payload.

Here's an example payload
```
{
  "data": {
    "type": "profile-subscription-bulk-create-job",
    "attributes": {
      "profiles": {
        "data": [
          {
            "type": "profile",
            "attributes": {
              "email": "matt-kemp@klaviyo-demo.com",
              "phone_number": "+15005550006",
              "subscriptions": {
                "sms": {
                  "marketing": {
                    "consent": "SUBSCRIBED"
                  }
                }
              }
            }
          }
        ]
      },
      "custom_source": "Calculator"
    },
    "relationships": {
      "list": {
        "data": {
          "type": "list",
          "id": "a list ID"
        }
      }
    }
  }
}
```
When I give that payload to `ProfilesApi.subscribeProfiles()` I get the error mentioned in 2 about the missing phone number. When I use the same payload via cURL there is no error.
If I change the payload to be an email subscription instead of sms the email is subscribed but I see the problem mentioned in 1. The `$source` profile property gets set to a value of `-9` for some reason and the "Subscribed to Email Marketing" event in the profile has `custom_method_detail` with a value of `null`.

**Comment by Ian-Montgomery-Klaviyo** [comment]
The SDK doesn't 1-1 use the name from the reference documentation. This is to match the standard typescript syntax, the objects are named with camelCase instead of snake_case. 

Switch `custom_source` to `customSource` and additionally `phone_number` to `phoneNumber`

**Comment by ericneubauerbumphealth** [comment]
Ah, I see! Thanks for letting me know. Must have missed that in the docs.
