### ISSUE TITLE
Daily limits from revisions 2024-07-15 in v 10.0.1 (revision 2024-05-15)

### ISSUE THREAD

**Issue by MarkAajuLarsen** [klaviyo/klaviyo-api-node#77]
Hi there, 

We are using the package at 10.0.1 and are getting rate limited when creating lists at a 100 items, when looking at the docs it looks like the latest revision has a daily limit of 100 but there is no mention of that limit in the revision we're using (2024-05-15), is there a possibility that the daily limits from the latest revision are also enforced for earlier revisions? 

Thanks.

**Comment by vpylypenko-klaviyo** [comment]
About a month ago, we introduced a daily limit of 100 lists that can be created per day. The latest version of the API documentation has been updated to reflect this new limit. However, this change also applies to all previous versions, including the one from 2024-05-15.
