### ISSUE TITLE
NPM package v12.0.0 missing dist/ folder

### ISSUE THREAD

**Issue by Adrien-P** [klaviyo/klaviyo-api-node#81]
In the latest release (v12.0.0) the `dist/` folder is missing in the npm package. 

It results in error messages like this when importing klaviyo-api:
`Failed to resolve entry for package "klaviyo-api". The package may have incorrect main/module/exports specified in its package.json.`

**Comment by ben-horgan-klaviyo** [comment]
Thanks for bringing this up- we'll release a patch shortly.

**Comment by ben-horgan-klaviyo** [comment]
This has been fixed in v12.0.1- sorry for the inconvenience!
```
npm update klaviyo-api
```
