### ISSUE TITLE
getProfiles API inconsistent name

### ISSUE THREAD

**Issue by fbahacker21** [klaviyo/klaviyo-api-node#87]
When I try to use the getProfiles API, the return object looks like this:

"data": [
{
type: 'profile',
id: '1234',
attributes: {
**"firstName": "Sarah"
"lastName": "Mason"}**
}]

while the api doc saying it should be:

"data": [
    {
      "type": "profile",
      "id": "01GDDKASAP8TKDDA2GRZDSVP4H",
      "attributes": {
        **"first_name": "Sarah",
        "last_name": "Mason"}**
}]

**Comment by BrandonKlaviyo** [comment]
Hi there, thanks for writing in. This looks to be expected behavior as we mention in our readme that camel case is used instead of the names you would typically see without the SDK per the Namespace section: https://github.com/klaviyo/klaviyo-api-node?tab=readme-ov-file#namespace
